apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster2
  region: us-west-2

vpc:
  id: "vpc-0342fbc17b6e2535e"
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-022ef13716dede47c
      my-new-stack-PublicSubnet02:
        id: subnet-0dfc3566f4b060415
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0dbf27deb306c481a
      my-new-stack-PrivateSubnet02:
        id: subnet-05278c77d9d8c9c16

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 1
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 0
    privateNetworking: true
